/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Tasks controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { TaskItemDto, RequestOptions, AuditEntryDto } from "../models";

@Injectable({ providedIn: "root" })
export class TasksService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiTasksTaskIdPut(taskId: string, taskItemDto: TaskItemDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiTasksTaskIdPut(taskId: string, taskItemDto: TaskItemDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiTasksTaskIdPut(taskId: string, taskItemDto: TaskItemDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiTasksTaskIdPut(taskId: string, taskItemDto: TaskItemDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tasks/${taskId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, taskItemDto, requestOptions);
    }

    apiTasksIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<TaskItemDto>;
    apiTasksIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TaskItemDto>>;
    apiTasksIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TaskItemDto>>;
    apiTasksIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tasks/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiTasksTaskIdAuditsGet(taskId: string, filter?: string, page?: number, size?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AuditEntryDto>>;
    apiTasksTaskIdAuditsGet(taskId: string, filter?: string, page?: number, size?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AuditEntryDto>>>;
    apiTasksTaskIdAuditsGet(taskId: string, filter?: string, page?: number, size?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AuditEntryDto>>>;
    apiTasksTaskIdAuditsGet(taskId: string, filter?: string, page?: number, size?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tasks/${taskId}/audits`;

        let params = new HttpParams();
        if (filter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, filter, 'filter');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'Page');
        }
        if (size != null) {
            params = HttpParamsBuilder.addToHttpParams(params, size, 'Size');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
